show_excerpts: False
collections:
  projects:
    output: true
  contributions:
    output: true

languages: ["en", "pt-br"]
exclude_from_localizations: ["assets", "_sass"]

title: Camila Maia
email: cmaiacd@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://camilamaia.github.io"
twitter_username: cmaiacd
github_username: camilamaia

# Build settings
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin
