show_excerpts: True
collections:
  projects:
    output: true
  contributions:
    output: true

title: Camila Maia
email: cmaiacd@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://camilamaia.github.io"
twitter_username: cmaiacd
github_username: camilamaia

# Build settings
plugins:
  - jekyll-feed
