title: Camila Maia
email: cmaiacd@gmail.com
description: >-
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: cmaiacd
linkedin_username: cmaiacd
github_username: camilamaia
mastodon:
  - username: cmaiacd
    instance: mastodon.social

show_excerpts: True

collections:
  projects:
    output: true
  Appearances:
    output: true

header_pages:
  - appearances.markdown
  - projects.markdown
  - blog.markdown

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
