title: Camila Maia
email: cmaiacd@gmail.com
description: >-
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: cmaiacd
linkedin_username: cmaiacd
github_username: camilamaia
mastodon:
  - username: cmaiacd
    instance: mastodon.social
google_analytics: G-TWFW32JJB6

show_excerpts: True

pagination:
  enabled: true
  per_page: 3
  permalink: '/:num/'
  title: ':title | :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

collections:
  projects:
    output: true
    order:
      - pyjamas-conf.md
      - scanapi.md
  appearances:
    output: true
    permalink: /appearances/:path/

header_pages:
  - appearances.md
  - projects.md
  - blog.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
